repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        name: Ensure files have end of file blank space
      - id: trailing-whitespace
        name: Trims extra whitespaces
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
        name: Yaml Formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.4
    hooks:
      - id: terraform_fmt
        name: Terraform Format
      - id: terragrunt_fmt
        name: Terragrunt Format
